/*
 * Copyright 2000-2013 JetBrains s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package rest.sandbox;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import java.util.Arrays;
import java.util.List;

@Path("/files")
public class FilesResource {
  // the resource JSON representation will be serialized by Jackson JAX-RS provider,
  // while the XML will still be generated by JAXB


  @Path("/array")
  @Produces({MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML})
  @GET
  public Bean[] getArray() {
    return new Bean[]{new Bean("a"), new Bean("b"), new Bean("c")};
  }

  @Path("/list")
  @Produces({MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML})
  @GET
  public List<Bean> getList() {
    return Arrays.asList(new Bean("a"), new Bean("b"), new Bean("c"));
  }

  @Path("/wrapper")
  @Produces({MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML})
  @GET
  public Beans getWrapper() {
    Beans ret = new Beans();
    ret.files = Arrays.asList(new Bean("a"), new Bean("b"), new Bean("c"));
    return ret;
  }
}
